"""Add index in maps tabel

Revision ID: c77b42ed720f
Revises: fc550b2d3be6
Create Date: 2026-04-07 15:47:49.538373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c77b42ed720f'
down_revision: Union[str, Sequence[str], None] = 'fc550b2d3be6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_maps_id'), 'maps', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_maps_id'), table_name='maps')
    # ### end Alembic commands ###
