"""Change type of bdate

Revision ID: e7c46165cb6e
Revises: ffea71b8ad43
Create Date: 2026-04-07 17:02:49.754090

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e7c46165cb6e"
down_revision: Union[str, Sequence[str], None] = "ffea71b8ad43"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "maps",
        "birth_date",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.String(),
        existing_nullable=False,
    )
    op.alter_column(
        "maps", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "maps", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "maps",
        "birth_date",
        existing_type=sa.String(),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
