"""Add index in maps tabel-change folder to add all models

Revision ID: f135fe481961
Revises: c77b42ed720f
Create Date: 2026-04-07 15:53:48.040057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f135fe481961'
down_revision: Union[str, Sequence[str], None] = 'c77b42ed720f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
