"""Add new column

Revision ID: ffea71b8ad43
Revises: f135fe481961
Create Date: 2026-04-07 16:50:36.384543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffea71b8ad43'
down_revision: Union[str, Sequence[str], None] = 'f135fe481961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('language', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('maps', 'language')
    # ### end Alembic commands ###
